### PR TITLE
Jngm8/publish data firebase

### PR DESCRIPTION
**Pull request by jngm8**
Publish post data to firebase done!

### CODE REVIEW

**Review by DanielOsorio01 — CHANGES_REQUESTED** [review]
Remove iOS folder

**Review by xavi-serrano — APPROVED** [review]

**Review by xavi-serrano — CHANGES_REQUESTED** [review]
Sacar carpeta iOS

**Review by jngm8 — COMMENTED** [review]
Tried to remove the iOS flutter and windows folders. Check

**Review by jngm8 — COMMENTED** [review]
Checked changes

**Review by DanielOsorio01 — APPROVED** [review]
LATM

**Pull request merged**
